#Home
GET http://localhost:5000

###

#Users
GET http://localhost:5000/users

###

#Create users
POST http://localhost:5000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "age": 25
}

###

#Delete users by ID
DELETE http://localhost:5000/users/insertidhere

###

#Update users by ID

PATCH http://localhost:5000/users/insertidhere
Content-Type: application/json

{
  "firstName": "Johnny",
  "age": "12"
}